[phases.setup]
nixPkgs = ["python39", "quarto"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["cd site && quarto render && cd .."]

[start]
cmd = "uvicorn app:app --host 0.0.0.0 --port $PORT"
